# Generated by Django 2.2 on 2019-11-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191104_0126'),
        ('accounts', '0004_auto_20191114_1917'),
    ]

    operations = [
    ]
