# Generated by Django 2.2 on 2019-10-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191010_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerissue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.Project', verbose_name='Проект'),
        ),
    ]
