# Generated by Django 2.2 on 2019-11-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerissue',
            name='assigned_to',
            field=models.ForeignKey(default=webapp.models.get_admin, on_delete=django.db.models.deletion.PROTECT, related_name='issues_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель задачи'),
        ),
        migrations.AddField(
            model_name='trackerissue',
            name='created_by',
            field=models.ForeignKey(default=webapp.models.get_admin, on_delete=django.db.models.deletion.PROTECT, related_name='issues_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_end',
            field=models.DateField(max_length=50, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_start',
            field=models.DateField(max_length=50, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trackerissue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues_project', to='webapp.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='trackerissue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues_status', to='webapp.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='trackerissue',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues_type', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
