# Generated by Django 2.2 on 2019-11-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20191107_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerissue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=webapp.models.get_admin, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель задачи'),
        ),
    ]
