# Generated by Django 2.2 on 2019-11-07 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20191107_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerissue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель задачи'),
        ),
    ]
