# Generated by Django 2.2 on 2019-11-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20191107_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_end',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Дата окончания'),
        ),
    ]
